# Setup
title:               CODE4PLC
tagline:             'Building better PLC software'
description:         'Statecharts in PLC world'
url:                 https://code4plc.github.io 
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Dragan Grujičić
  url:               https://code4plc.github.io
  email:             dragan.grujicic@outlook.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
github_repo:         https://github.com/code4plc/code4plc.github.io
